### ISSUE TITLE
Search fails for some subtitles

### ISSUE THREAD

**Issue by Pmaene** [michaelbaudino/addic7ed-ruby#20]
Currently, subtitles for some shows cannot be found, although they are available on Addic7ed. Examples are "DC's Legends of Tomorrow" and "The Flash (2015)"? In both cases, the release name extracted from the video file differs slightly from the name used on Addic7ed.

**Comment by michaelbaudino** [comment]
Should be fixed in [2.0.0](https://rubygems.org/gems/addic7ed/versions/2.0.0)

**Comment by Pmaene** [comment]
That was quick, thanks!

**Comment by michaelbaudino** [comment]
Oops, it was actually not. It should now really be fixed in [2.0.1](https://rubygems.org/gems/addic7ed/versions/2.0.1) :wink:

**Comment by michaelbaudino** [comment]
This is getting very embarassing, but `2.0.1` is still flawed when the filename doesn't contain a production year but Addic7ed expect one (like for American Crime). Also, there's a shameful `MethodMissing` error due to a bad renaming :disappointed_relieved: 

Anyway, both bugs are fixed in `2.0.2` :+1: 

Please give me any feedback you may have, but i think it's getting quite stable :wink: 
Also, the code should now be more open to extension / enhancement.

**Comment by Pmaene** [comment]
It runs perfectly, thanks for all the hard work! I will let you know if I stumble upon any bugs.

**Comment by nicolasvergoz** [comment]
I actually developped my own addic7ed gem (inspired by your gem) based on that issue.
I looking for the best matching score between the title extracted from filename and the show title from addic7ed. Check it out [get-addic7ed](https://github.com/nicolasvergoz/get-addic7ed)
I also looking for failed match so if you want to test it, be my guest. (I'm learning Rspec currently)

**Comment by michaelbaudino** [comment]
Neat, @nicolasvergoz  :sparkles: 

I'm glad to inspire other projects :blush:
